package com.oljubuncic.model;

// Generated 03-Mar-2015 23:19:13 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ContactPurpose generated by hbm2java
 */
@Entity
@Table(name = "contact_purpose")
public class ContactPurpose implements java.io.Serializable {

	private int id;
	private String name;
	private String description;
	private Set emails = new HashSet(0);
	private Set phones = new HashSet(0);

	public ContactPurpose() {
	}

	public ContactPurpose(int id, String name, String description) {
		this.id = id;
		this.name = name;
		this.description = description;
	}

	public ContactPurpose(int id, String name, String description, Set emails,
			Set phones) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.emails = emails;
		this.phones = phones;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contactPurpose")
	public Set getEmails() {
		return this.emails;
	}

	public void setEmails(Set emails) {
		this.emails = emails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contactPurpose")
	public Set getPhones() {
		return this.phones;
	}

	public void setPhones(Set phones) {
		this.phones = phones;
	}

}
