package com.oljubuncic.model;

// Generated 03-Mar-2015 23:19:13 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Email generated by hbm2java
 */
@Entity
@Table(name = "email")
public class Email implements java.io.Serializable {

	private int id;
	private ContactPurpose contactPurpose;
	private Facility facility;
	private String address;

	public Email() {
	}

	public Email(int id, ContactPurpose contactPurpose, Facility facility,
			String address) {
		this.id = id;
		this.contactPurpose = contactPurpose;
		this.facility = facility;
		this.address = address;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "contact_purpose_id", nullable = false)
	public ContactPurpose getContactPurpose() {
		return this.contactPurpose;
	}

	public void setContactPurpose(ContactPurpose contactPurpose) {
		this.contactPurpose = contactPurpose;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "facility_id", nullable = false)
	public Facility getFacility() {
		return this.facility;
	}

	public void setFacility(Facility facility) {
		this.facility = facility;
	}

	@Column(name = "address", nullable = false)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
