package com.oljubuncic.model;

// Generated 03-Mar-2015 23:19:13 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Facility generated by hbm2java
 */
@Entity
@Table(name = "facility")
public class Facility implements java.io.Serializable {

	private int id;
	private String name;
	private String description;
	private String website;
	private Set facilityCategories = new HashSet(0);
	private Set phones = new HashSet(0);
	private Set emails = new HashSet(0);
	private Set facilityAddresses = new HashSet(0);

	public Facility() {
	}

	public Facility(int id, String name, String description, String website) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.website = website;
	}

	public Facility(int id, String name, String description, String website,
			Set facilityCategories, Set phones, Set emails,
			Set facilityAddresses) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.website = website;
		this.facilityCategories = facilityCategories;
		this.phones = phones;
		this.emails = emails;
		this.facilityAddresses = facilityAddresses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", nullable = false)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "website", nullable = false)
	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "facility")
	public Set getFacilityCategories() {
		return this.facilityCategories;
	}

	public void setFacilityCategories(Set facilityCategories) {
		this.facilityCategories = facilityCategories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "facility")
	public Set getPhones() {
		return this.phones;
	}

	public void setPhones(Set phones) {
		this.phones = phones;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "facility")
	public Set getEmails() {
		return this.emails;
	}

	public void setEmails(Set emails) {
		this.emails = emails;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "facility")
	public Set getFacilityAddresses() {
		return this.facilityAddresses;
	}

	public void setFacilityAddresses(Set facilityAddresses) {
		this.facilityAddresses = facilityAddresses;
	}

}
