package pojo;

// Generated 03-Mar-2015 23:19:13 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category")
public class Category implements java.io.Serializable {

	private int id;
	private Category category;
	private String name;
	private Set facilityCategories = new HashSet(0);
	private Set categories = new HashSet(0);

	public Category() {
	}

	public Category(int id, Category category, String name) {
		this.id = id;
		this.category = category;
		this.name = name;
	}

	public Category(int id, Category category, String name,
			Set facilityCategories, Set categories) {
		this.id = id;
		this.category = category;
		this.name = name;
		this.facilityCategories = facilityCategories;
		this.categories = categories;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_category_id", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	public Set getFacilityCategories() {
		return this.facilityCategories;
	}

	public void setFacilityCategories(Set facilityCategories) {
		this.facilityCategories = facilityCategories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
	public Set getCategories() {
		return this.categories;
	}

	public void setCategories(Set categories) {
		this.categories = categories;
	}

}
