package pojo;

// Generated 03-Mar-2015 23:19:13 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FacilityCategory generated by hbm2java
 */
@Entity
@Table(name = "facility_category")
public class FacilityCategory implements java.io.Serializable {

	private int id;
	private Category category;
	private Facility facility;

	public FacilityCategory() {
	}

	public FacilityCategory(int id, Category category, Facility facility) {
		this.id = id;
		this.category = category;
		this.facility = facility;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "facility_id", nullable = false)
	public Facility getFacility() {
		return this.facility;
	}

	public void setFacility(Facility facility) {
		this.facility = facility;
	}

}
