package com.oljubuncic1.entities;

// Generated 03-Mar-2015 23:19:13 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */

@Entity
@Table(name = "address")
public class Address implements java.io.Serializable {

	private int id;
	private City city;
	private String houseNumber;
	private String street;
	private String postalCode;
	private Set<Facility> facilities = new HashSet<Facility>(0);

	public Address() {
	}

	public Address(int id, City city, String houseNumber, String street,
			String postalCode) {
		this.id = id;
		this.city = city;
		this.houseNumber = houseNumber;
		this.street = street;
		this.postalCode = postalCode;
	}

	public Address(int id, City city, String houseNumber, String street,
			String postalCode, Set<Facility> facilities) {
		this.id = id;
		this.city = city;
		this.houseNumber = houseNumber;
		this.street = street;
		this.postalCode = postalCode;
		this.facilities= facilities;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "city_id", nullable = false)
	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	@Column(name = "house_number", nullable = false)
	public String getHouseNumber() {
		return this.houseNumber;
	}

	public void setHouseNumber(String houseNumber) {
		this.houseNumber = houseNumber;
	}

	@Column(name = "street", nullable = false)
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "postal_code", nullable = false)
	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	@ManyToMany(fetch = FetchType.EAGER, mappedBy = "addresses")
	public Set<Facility> getFacilities() {
		return this.facilities;
	}

	public void setFacilities(Set<Facility> facilities) {
		this.facilities = facilities;
	}

}
