package com.oljubuncic1.entities;

// Generated 03-Mar-2015 23:19:13 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Phone generated by hbm2java
 */
@Entity
@Table(name = "phone")
public class Phone implements java.io.Serializable {

	private int id;
	private ContactPurpose contactPurpose;
	private Facility facility;
	private String number;
	private String type;

	public Phone() {
	}

	public Phone(int id, String number, String type, Facility facility) {
		this.id = id;
		//this.contactPurpose = contactPurpose;
		this.facility = facility;
		this.number = number;
		this.type = type;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "contact_purpose_id", nullable = true)
	public ContactPurpose getContactPurpose() {
		return this.contactPurpose;
	}

	public void setContactPurpose(ContactPurpose contactPurpose) {
		this.contactPurpose = contactPurpose;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "facility_id", nullable = true)
	public Facility getFacility() {
		return this.facility;
	}

	public void setFacility(Facility facility) {
		this.facility = facility;
	}

	@Column(name = "number", nullable = false)
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	@Column(name = "type", nullable = false)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
